### ISSUE TITLE
how to use cloud-table ?

### ISSUE THREAD

**Issue by sandys** [mrphu3074/cloud-table#1]
hi,
we are looking at cloud table - not able to figure how to run the example ?

we are trying to build an excel component. can you please advise.

**Comment by mrphu3074** [comment]
hi @sandys 

For now, I don't have time to finish this project. Sorry about that.
You can take a look at https://bvaughn.github.io/react-virtualized
This lib can give you abilities to build your table (excel style) with performance.

Example: https://bvaughn.github.io/react-virtualized/#/components/ArrowKeyStepper

**Comment by sandys** [comment]
Thanks for replying. But how to test code that you already written (in this
repo). I don't know how to run. I tried yarn start

**Comment by mrphu3074** [comment]
You can try:
```bash
git clone -b dev https://github.com/mrphu3074/cloud-table.git
cd cloud-table
# If you are using yarn
yarn
yarn build
yarn storybook 
# NPM
npm install
npm run build
npm run storybook

# Then you can view a demo http://localhost:6006/
```

What I did are experimental. I am so sorry if you get trouble with it :D
